Indent RUN commands for better readablity

diff --git a/containers/docker_mini/Dockerfile b/containers/docker_mini/Dockerfile
--- a/containers/docker_mini/Dockerfile
+++ b/containers/docker_mini/Dockerfile
@@ -52,12 +52,12 @@ RUN mkdir /MNT
 ARG pythiaV="8310"
 ENV PYTHIA8=/SMASH/pythia_install/
 RUN wget https://pythia.org/download/pythia83/pythia${pythiaV}.tgz && \
-tar xf pythia${pythiaV}.tgz && rm pythia${pythiaV}.tgz && \
-cd pythia${pythiaV} && \
-./configure --cxx-common="${C_CXX_ARCH_FLAG} -O3 -std=c++17 -fPIC -pthread" --prefix=${PYTHIA8} && \
-make -j$(nproc) && \
-make install && \
-echo ${PYTHIA8}/lib >> /etc/ld.so.conf && ldconfig
+    tar xf pythia${pythiaV}.tgz && rm pythia${pythiaV}.tgz && \
+    cd pythia${pythiaV} && \
+    ./configure --cxx-common="${C_CXX_ARCH_FLAG} -O3 -std=c++17 -fPIC -pthread" --prefix=${PYTHIA8} && \
+    make -j$(nproc) && \
+    make install && \
+    echo ${PYTHIA8}/lib >> /etc/ld.so.conf && ldconfig
 
 ENV PYTHIA8DATA=$PYTHIA8/share/Pythia8/xmldoc
 ENV PYTHIA_LIBRARY=$PYTHIA8/lib
@@ -68,11 +68,11 @@ ENV PATH=$PYTHIA8/bin:$PATH
 # Get and build public SMASH
 
 RUN cd /SMASH && git clone https://github.com/smash-transport/smash.git && \
-mkdir -p smash/build && \
-mkdir -p smash_bin && \
-cd smash/build && \
-cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS="${C_CXX_ARCH_FLAG}" \
--DCMAKE_CXX_FLAGS="${C_CXX_ARCH_FLAG}" || echo "cmake SMASH build configuration failed!"
+    mkdir -p smash/build && \
+    mkdir -p smash_bin && \
+    cd smash/build && \
+    cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS="${C_CXX_ARCH_FLAG}" \
+    -DCMAKE_CXX_FLAGS="${C_CXX_ARCH_FLAG}" || echo "cmake SMASH build configuration failed!"
 RUN cd /SMASH/smash/build && make smash -j$(nproc) || echo "make SMASH compilation failed!"
 RUN <<EOF
 if [ -f /SMASH/smash/build/smash ]
