Fix typo and reorder compilation flags
In addition, compile Julia from sources

diff --git a/containers/docker_mini/Dockerfile b/containers/docker_mini/Dockerfile
--- a/containers/docker_mini/Dockerfile
+++ b/containers/docker_mini/Dockerfile
@@ -6,10 +6,8 @@ FROM ubuntu:22.04
 
 SHELL ["/bin/bash", "-c"]
 
-# Set the proper general cpu family architecture flag for the compiler,
-# in most cases either "x86-64" (for Intel/AMD cpus) or "arm64" (for ARM processors in Apple computers).
-# Please, note that, if you are not interested in the portability on other cpus, you can choose more specific flags
-# (e.g. "native" if you plan to run the container only on cpus like the one used for the the creation of its image).
+# Set the proper general cpu family architecture flag.
+# Please, for more information refer to the documention of your compiler.
 
 ARG TARGET_ARCHITECTURE="x86-64"
 
@@ -35,11 +33,9 @@ rsync \
 wget \
 vim
 
-# Set generic optimization, architecture and desired version of C++-standard flags for compilation using makefiles.
+# Set cpu architecture flag for compilation
 
-ARG CPPFLAGS="-O3 -march=${TARGET_ARCHITECTURE} --std=c++17"
-ARG CXXFLAGS=${CPPFLAGS}
-ARG CFLAGS="-O3 -march=${TARGET_ARCHITECTURE}"
+ARG C_CXX_ARCH_FLAG="-march=${TARGET_ARCHITECTURE}"
 
 # Create main project directory
 
@@ -56,7 +52,7 @@ ENV PYTHIA8=/SMASH/pythia_install/
 RUN wget https://pythia.org/download/pythia83/pythia${pythiaV}.tgz && \
 tar xf pythia${pythiaV}.tgz && rm pythia${pythiaV}.tgz && \
 cd pythia${pythiaV} && \
-./configure --cxx-common="${CPPFLAGS} -fPIC -pthread" --prefix=${PYTHIA8} && \
+./configure --cxx-common="${C_CXX_ARCH_FLAG} -O3 -std=c++17 -fPIC -pthread" --prefix=${PYTHIA8} && \
 make -j$(nproc) && \
 make install && \
 echo ${PYTHIA8}/lib >> /etc/ld.so.conf && ldconfig
@@ -73,8 +69,8 @@ RUN cd /SMASH && git clone https://github.com/smash-transport/smash.git && \
 mkdir -p smash/build && \
 mkdir -p smash_bin && \
 cd smash/build && \
-cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS=${CFLAGS} -DCMAKE_CXX_FLAGS=${CXXFLAGS} \
-|| echo "cmake SMASH build configuration failed!"
+cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS="${C_CXX_ARCH_FLAG}" \
+-DCMAKE_CXX_FLAGS="${C_CXX_ARCH_FLAG}" || echo "cmake SMASH build configuration failed!"
 RUN cd /SMASH/smash/build && make smash -j$(nproc) || echo "make SMASH compilation failed!"
 RUN <<EOF
 if [ -f /SMASH/smash/build/smash ]
