Add validation and information of tuning architecture to images

diff --git a/containers/docker_max/Dockerfile b/containers/docker_max/Dockerfile
--- a/containers/docker_max/Dockerfile
+++ b/containers/docker_max/Dockerfile
@@ -51,7 +51,18 @@ LABEL org.opencontainers.image.authors="SMASH team"
 LABEL org.opencontainers.image.url="https://smash-transport.github.io"
 LABEL org.opencontainers.image.source="https://github.com/smash-transport/smash"
 LABEL org.opencontainers.image.description="\
-SMASH with ROOT ${ROOT_VERSION}, HepMC3 ${HEPMC_VERSION}, Rivet ${RIVET_VERSION} and several other tools"
+SMASH with ROOT ${ROOT_VERSION}, HepMC3 ${HEPMC_VERSION}, Rivet ${RIVET_VERSION}\
+ and several other tools (tuned for ${TARGET_ARCHITECTURE} architecture)."
+
+# Fail if TARGET_ARCHITECTURE is set to "native" (this is not allowed in this Dockerfile
+# since it would make the image non portable)
+
+RUN <<EOF
+  if [[ "$TARGET_ARCHITECTURE" = "native" ]]; then
+    echo "ERROR: TARGET_ARCHITECTURE cannot be 'native'" >&2
+    exit 1
+  fi
+EOF
 
 # Update the distribution installing several additional packages non interactively
 
diff --git a/containers/docker_mini/Dockerfile b/containers/docker_mini/Dockerfile
--- a/containers/docker_mini/Dockerfile
+++ b/containers/docker_mini/Dockerfile
@@ -19,7 +19,18 @@ LABEL org.opencontainers.image.authors="SMASH team"
 LABEL org.opencontainers.image.url="https://smash-transport.github.io"
 LABEL org.opencontainers.image.source="https://github.com/smash-transport/smash"
 LABEL org.opencontainers.image.description="\
-Basic SMASH image (sources, compiler and bare executable, without ROOT, HepMC3 and Rivet)."
+Basic SMASH image tuned for ${TARGET_ARCHITECTURE} architecture\
+ (sources, compiler and bare executable, without ROOT, HepMC3 and Rivet)."
+
+# Fail if TARGET_ARCHITECTURE is set to "native" (this is not allowed in this Dockerfile
+# since it would make the image non portable)
+
+RUN <<EOF
+  if [[ "$TARGET_ARCHITECTURE" = "native" ]]; then
+    echo "ERROR: TARGET_ARCHITECTURE cannot be 'native'" >&2
+    exit 1
+  fi
+EOF
 
 # Install minimal set of requirements
 
